---
- name: Create credential directory 
  file:
    path: /home/opeadmin/greengrass-v2-credentials
    state: directory
    owner: "root"
    group: "root"
    mode: "775"

- name: Configure your AWS credentials
  template:
    src: credentials.j2
    dest: /home/opeadmin/greengrass-v2-credentials/credentials
    owner: root
    group: root
    mode: 0664