- name: Create certification directory 
  file:
    path: "{{ CERTS_PATH }}"
    state: directory
    mode: "776"

- name: Copy certification file
  copy:
    src: "{{ lookup('ansible.builtin.env','HOME') }}/workspace/2023-k8s-Team/ansible/cert/{{ IOT_THING_NAME }}/device.pem.crt"
    dest: "{{ CERTS_PATH }}/device.pem.crt"
    mode: "776"

- name: Copy key file
  copy:
    src: "{{ lookup('ansible.builtin.env','HOME') }}/workspace/2023-k8s-Team/ansible/cert/{{ IOT_THING_NAME }}/private.pem.key"
    dest: "{{ CERTS_PATH }}/private.pem.key"
    mode: "776"

- name: Download root CA certificate
  ansible.builtin.shell: |
    wget https://www.amazontrust.com/repository/AmazonRootCA1.pem -O AmazonRootCA1.pem
  args:
    chdir: "{{ CERTS_PATH }}"
