---
- name: Greengrass v2 deployment file
  template:
    src: greengrass-v2-deployment.j2
    dest: "{{ lookup('ansible.builtin.env','HOME') }}/greengrass-v2-deployment.yaml"

- name: Download kubernetes installer
  shell:
    cmd: "kubectl apply -f {{ lookup('ansible.builtin.env','HOME') }}/greengrass-v2-deployment.yaml"
