---
- name: Setup kubernetes server
  hosts: k3ssv
  gather_facts: true
  become: true

  roles:
    - role: k3s_server
      tags: k3s_server
        
- name: Setup kubernetes agents
  hosts: agents
  gather_facts: true
  become: true

  roles:
    - role: k3s_agent

