---
- name: Setup kubernetes server
  hosts: k3ssv
  gather_facts: true
  become: true

  roles:
    - role: k3s_server
      tags: k3s_server
        
- name: Setup kubernetes agents
  hosts: agents
  gather_facts: true
  become: true

  roles:
    - role: k3s_agent
      tags: k3s_agent

- name: Setup Greengrass Core
  hosts: k3sgw
  gather_facts: true
  become: true

  roles:
    - role: greengrass_setup
      tags: greengrass_setup

- name: Deployment Greengrass Core with kubernetes
  hosts: k3ssv
  gather_facts: true
  become: false

  roles:
    - role: greengrass_deployment
      tags: greengrass_deployment