- name: Install nodejs
  ansible.builtin.apt:
    name: nodejs npm
    state: present
  become: true

- name: Update Node.js to Latest Version
  ansible.builtin.shell: |
    npm -g install n
    n stable
  become: true

- name: Update Node.js to Latest Version
  ansible.builtin.shell: sudo npm install -g aws-cdk
  become: true

- name: Uninstall AWS CLI
  ansible.builtin.shell: |
    sudo rm /usr/local/bin/aws
    sudo rm /usr/local/bin/aws_completer
    sudo rm -rf /usr/local/aws-cli
    sudo rm -rf ~/.aws/
  become: true

- name: Install AWS CLI aarch64
  ansible.builtin.shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  become: true
  when: ansible_architecture == "aarch64"

- name: Install AWS CLI x86_64
  ansible.builtin.shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  become: true
  when: ansible_architecture == "x86_64"

- name: Create credential directory 
  file:
    path: /home/opeadmin/.aws/
    state: directory
    mode: "775"

- name: Configure your AWS credentials
  template:
    src: credentials.j2
    dest: /home/opeadmin/.aws/credentials
    mode: 0664

- name: Configure your AWS config file
  template:
    src: config.j2
    dest: /home/opeadmin/.aws/config
    mode: 0664
